-- Транзакции Click SHOP API (аналог payme_transactions).
-- Применить в Supabase (SQL editor) до включения Click.
create table if not exists public.click_transactions (
  id                uuid primary key default gen_random_uuid(),
  click_trans_id    text not null,
  click_paydoc_id   text,
  merchant_trans_id uuid not null references public.rentals(id) on delete cascade,
  amount            numeric not null,           -- в СУМАХ
  state             int  not null default 1,    -- 1=prepared, 2=confirmed, -1=cancelled
  sign_time         text,
  prepare_time      bigint,
  confirm_time      bigint,
  cancel_time       bigint,
  created_at        timestamptz not null default now()
);

create index if not exists click_tx_merchant_trans on public.click_transactions(merchant_trans_id);

-- merchant_prepare_id, который мы возвращаем Click в Prepare — ЧИСЛОВОЙ prepare_id
-- (Click SHOP API ждёт integer, uuid не годится). В Complete ищем строку по нему.
-- Идемпотентность Prepare: click_trans_id уникален.
-- (накатано в Supabase миграцией payment_provider_and_click_prepare_id, 05.08.2026)
alter table public.click_transactions add column if not exists prepare_id bigint generated by default as identity;
create unique index if not exists click_tx_prepare_id_uniq on public.click_transactions(prepare_id);
create unique index if not exists click_tx_click_trans_uniq on public.click_transactions(click_trans_id);

-- Провайдер оплаты аренды (для payment_url при поллинге из приложения)
alter table public.rentals add column if not exists payment_provider text not null default 'payme';
